//! Build script: rasterizes battery icon SVGs from `assets/icons/` into
//! static ARGB32 pixel arrays embedded in the binary.
//!
//! Output: `$OUT_DIR/icons_generated.rs`, included by `src/tray/icons.rs`.
//! Regenerated whenever any file under `assets/icons/` changes.
//!
//! The SNI protocol's `icon_pixmap` field expects ARGB32 in network byte
//! order (big-endian): each pixel is four bytes `[A, R, G, B]`.
//! tiny-skia produces premultiplied RGBA `[R_pm, G_pm, B_pm, A]`, so we
//! un-premultiply and reorder before writing the arrays.

use std::fmt::Write as FmtWrite;
use std::path::PathBuf;

/// Pixel sizes to rasterize. The compositor picks the closest available size.
const SIZES: &[u32] = &[16, 22, 32];

/// Battery levels for which we have SVG assets (5% granularity).
const LEVELS: &[u8] = &[
    0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100,
];

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let icons_dir = manifest_dir.join("assets").join("icons");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());

    println!("cargo:rerun-if-changed=assets/icons");

    let mut out = String::from(
        "// @generated by build.rs — do not edit manually.\n\
         // Source: assets/icons/*.svg\n\n\
         pub struct EmbeddedIcon {\n\
             pub width: i32,\n\
             pub height: i32,\n\
             /// Pixel data in ARGB32 network byte order: [A, R, G, B] per pixel.\n\
             pub argb32: &'static [u8],\n\
         }\n\n",
    );

    // Render all levels for both discharging and charging variants.
    for &charging in &[false, true] {
        for &level in LEVELS {
            let stem = if charging {
                format!("battery_charging_{}", level)
            } else {
                format!("battery_{}", level)
            };
            let const_base = stem.to_uppercase();
            let svg_path = icons_dir.join(format!("{}.svg", stem));

            let svg_data = std::fs::read(&svg_path).unwrap_or_else(|e| {
                panic!("build.rs: failed to read {}: {}", svg_path.display(), e)
            });

            let tree = {
                let opts = resvg::usvg::Options::default();
                resvg::usvg::Tree::from_data(&svg_data, &opts).unwrap_or_else(|e| {
                    panic!("build.rs: failed to parse {}: {}", svg_path.display(), e)
                })
            };

            for &size in SIZES {
                let sx = size as f32 / tree.size().width();
                let sy = size as f32 / tree.size().height();
                let transform = resvg::tiny_skia::Transform::from_scale(sx, sy);

                let mut pixmap = resvg::tiny_skia::Pixmap::new(size, size)
                    .expect("build.rs: failed to create pixmap");

                resvg::render(&tree, transform, &mut pixmap.as_mut());

                let argb = premul_rgba_to_argb32(pixmap.data());
                let const_name = format!("{}_{}", const_base, size);

                writeln!(
                    out,
                    "pub static {}: EmbeddedIcon = EmbeddedIcon {{\n\
                     \x20   width: {},\n\
                     \x20   height: {},\n\
                     \x20   argb32: &{:?},\n\
                     }};\n",
                    const_name, size, size, argb
                )
                .unwrap();
            }
        }
    }

    // Generate the lookup function so icon.rs stays simple.
    // Level is snapped to nearest 5% before lookup.
    writeln!(
        out,
        "/// Look up the correct icon for a battery level and state."
    )
    .unwrap();
    writeln!(out, "///").unwrap();
    writeln!(
        out,
        "/// `level` is rounded to the nearest 5% step. Values above 100 are clamped."
    )
    .unwrap();
    writeln!(
        out,
        "pub fn get_icon(level: u8, charging: bool, size: u32) -> &'static EmbeddedIcon {{"
    )
    .unwrap();
    writeln!(
        out,
        "    // Round to nearest 5, cap at 100. Widened to u16 to avoid u8 overflow."
    )
    .unwrap();
    writeln!(
        out,
        "    let snapped = (((level as u16 + 2) / 5) * 5).min(100) as u8;"
    )
    .unwrap();
    writeln!(out, "    match (snapped, charging, size) {{").unwrap();

    for &charging in &[false, true] {
        for &level in LEVELS {
            let const_base = if charging {
                format!("BATTERY_CHARGING_{}", level)
            } else {
                format!("BATTERY_{}", level)
            };
            writeln!(
                out,
                "        ({}, {}, 16) => &{}_16,",
                level, charging, const_base
            )
            .unwrap();
            writeln!(
                out,
                "        ({}, {}, 22) => &{}_22,",
                level, charging, const_base
            )
            .unwrap();
            writeln!(
                out,
                "        ({}, {}, _)  => &{}_32,",
                level, charging, const_base
            )
            .unwrap();
        }
    }

    writeln!(
        out,
        "        _ => &BATTERY_0_32, // unreachable after snap+clamp"
    )
    .unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();

    std::fs::write(out_dir.join("icons_generated.rs"), out)
        .expect("build.rs: failed to write icons_generated.rs");
}

/// Convert tiny-skia's premultiplied RGBA to ARGB32 network byte order.
///
/// tiny-skia pixel layout: `[R_premul, G_premul, B_premul, A]`
/// SNI icon_pixmap layout: `[A, R, G, B]` (big-endian uint32)
fn premul_rgba_to_argb32(data: &[u8]) -> Vec<u8> {
    let mut out = Vec::with_capacity(data.len());
    for px in data.chunks_exact(4) {
        let (r_pm, g_pm, b_pm, a) = (px[0], px[1], px[2], px[3]);
        let (r, g, b) = if a == 0 {
            (0u8, 0u8, 0u8)
        } else {
            let a32 = a as u32;
            (
                ((r_pm as u32 * 255 + a32 / 2) / a32) as u8,
                ((g_pm as u32 * 255 + a32 / 2) / a32) as u8,
                ((b_pm as u32 * 255 + a32 / 2) / a32) as u8,
            )
        };
        out.extend_from_slice(&[a, r, g, b]);
    }
    out
}
