//! Build script: rasterizes battery icon SVGs from `assets/icons/` into
//! static ARGB32 pixel arrays embedded in the binary.
//!
//! Output: `$OUT_DIR/icons_generated.rs`, included by `src/tray/icon.rs`.
//! Regenerated whenever any file under `assets/icons/` changes.
//!
//! The SNI protocol's `icon_pixmap` field expects ARGB32 in network byte
//! order (big-endian): each pixel is four bytes `[A, R, G, B]`.
//! tiny-skia produces premultiplied RGBA `[R_pm, G_pm, B_pm, A]`, so we
//! un-premultiply and reorder before writing the arrays.

use std::fmt::Write as FmtWrite;
use std::path::PathBuf;

/// Pixel sizes to rasterize. The compositor picks the closest available size.
const SIZES: &[u32] = &[16, 22, 32];

/// (filename_stem, const_name_base)
const VARIANTS: &[(&str, &str)] = &[
    ("battery_0", "BATTERY_0"),
    ("battery_1", "BATTERY_1"),
    ("battery_2", "BATTERY_2"),
    ("battery_3", "BATTERY_3"),
    ("battery_4", "BATTERY_4"),
    ("battery_5", "BATTERY_5"),
    ("battery_full", "BATTERY_FULL"),
    ("battery_charging_0", "BATTERY_CHARGING_0"),
    ("battery_charging_1", "BATTERY_CHARGING_1"),
    ("battery_charging_2", "BATTERY_CHARGING_2"),
    ("battery_charging_3", "BATTERY_CHARGING_3"),
    ("battery_charging_4", "BATTERY_CHARGING_4"),
    ("battery_charging_5", "BATTERY_CHARGING_5"),
    ("battery_charging_full", "BATTERY_CHARGING_FULL"),
];

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let icons_dir = manifest_dir.join("assets").join("icons");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());

    // Rerun if any SVG changes or a new one is added.
    println!("cargo:rerun-if-changed=assets/icons");

    let mut out = String::from(
        "// @generated by build.rs — do not edit manually.\n\
         // Source: assets/icons/*.svg\n\n\
         pub struct EmbeddedIcon {\n\
             pub width: i32,\n\
             pub height: i32,\n\
             /// Pixel data in ARGB32 network byte order: [A, R, G, B] per pixel.\n\
             pub argb32: &'static [u8],\n\
         }\n\n",
    );

    for (stem, const_base) in VARIANTS {
        let svg_path = icons_dir.join(format!("{}.svg", stem));

        let svg_data = std::fs::read(&svg_path)
            .unwrap_or_else(|e| panic!("build.rs: failed to read {}: {}", svg_path.display(), e));

        let tree = {
            let opts = resvg::usvg::Options::default();
            resvg::usvg::Tree::from_data(&svg_data, &opts).unwrap_or_else(|e| {
                panic!("build.rs: failed to parse {}: {}", svg_path.display(), e)
            })
        };

        for &size in SIZES {
            let sx = size as f32 / tree.size().width();
            let sy = size as f32 / tree.size().height();
            let transform = resvg::tiny_skia::Transform::from_scale(sx, sy);

            let mut pixmap = resvg::tiny_skia::Pixmap::new(size, size)
                .expect("build.rs: failed to create pixmap");

            resvg::render(&tree, transform, &mut pixmap.as_mut());

            let argb = premul_rgba_to_argb32(pixmap.data());
            let const_name = format!("{}_{}", const_base, size);

            writeln!(
                out,
                "pub static {}: EmbeddedIcon = EmbeddedIcon {{\n\
                 \x20   width: {},\n\
                 \x20   height: {},\n\
                 \x20   argb32: &{:?},\n\
                 }};\n",
                const_name, size, size, argb
            )
            .unwrap();
        }
    }

    std::fs::write(out_dir.join("icons_generated.rs"), out)
        .expect("build.rs: failed to write icons_generated.rs");
}

// Convert tiny-skia's premultiplied RGBA to ARGB32 network byte order.
//
// tiny-skia pixel layout: `[R_premul, G_premul, B_premul, A]`
// SNI icon_pixmap layout: `[A, R, G, B]` (big-endian uint32)
fn premul_rgba_to_argb32(data: &[u8]) -> Vec<u8> {
    let mut out = Vec::with_capacity(data.len());
    for px in data.chunks_exact(4) {
        let (r_pm, g_pm, b_pm, a) = (px[0], px[1], px[2], px[3]);
        let (r, g, b) = if a == 0 {
            (0u8, 0u8, 0u8)
        } else {
            let a32 = a as u32;
            (
                ((r_pm as u32 * 255 + a32 / 2) / a32) as u8,
                ((g_pm as u32 * 255 + a32 / 2) / a32) as u8,
                ((b_pm as u32 * 255 + a32 / 2) / a32) as u8,
            )
        };
        out.extend_from_slice(&[a, r, g, b]);
    }
    out
}
